#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(
      command \
        -v \
        "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  make_date=""
  target_command=""
  project_dir=""
  contracts_dir=""
  work_dir=""
  compiler_backend=""
  lib_dir=""
  cache_clean=""
  rebuild_skip=""
  target_languages=()
  target_languages_amount=""
  command_args=()
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'solidity-compiler'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/evm-make"
  echo \
    "${_dir}"
}

_work_dir_auto_detect() {
  local \
    _dir
  _dir="${HOME}/.cache/evm-make"
  echo \
    "${_dir}"
}

_versions_get() {
  local \
    _contract_dirs=() \
    _dir \
    _dir_basename \
    _re
  _contract_dirs+=(
    "$@"
  )
  _re='^[0-9][0-9.]*$'
  for _dir in "${_contract_dirs[@]}"; do
    _dir_basename="$(
      basename \
        "${_dir}")"
    if [[ ${_dir_basename} =~ ${_re} ]] ; then
      _contract_versions+=(
        "${_dir_basename}"
      )
    fi
  done
}

_contract_setup() {
  local \
    _contracts_dir="${1}" \
    _target_contract="${2}" \
    _network \
    _item
  _sol="${_target_contract}.sol"
  _abi="${_target_contract}.abi.json"
  _bytecode="${_target_contract}.bin"
  _json="${_target_contract}.json"
  _contract_dir="${_project_dir}/${_contracts_dir}/${_target_contract}"
  _contract_deployments_dir="${_contract_dir}/deployments"
  if [[ -d "${_contract_deployments_dir}" ]]; then
    _msg=(
      "Contract dir: '${_contract_dir}'."
    )
    _msg_info \
      "${_msg[*]}"
    _msg=(
      "Deployments dir: '${_contract_deployments_dir}'."
    )
    _msg_info \
      "${_msg[*]}"
    _contract_dirs=(
      "${_contract_dir}/"*
    )
    _msg_info \
      "Found contract directories: '${_contract_dirs[*]}'."
    _versions_get \
      "${_contract_dirs[@]}"
    _msg_info \
      "Found versions: ${_contract_versions[*]}"
    for _item in "${_contract_deployments_dir}/"*; do
      if [[ -d "${_item}" ]]; then
        _contract_deployed_networks_config_dirs=(
          "${_item}"
        )
      fi;
    done
  fi
  for _network \
    in "${_contract_deployed_networks_config_dirs[@]}"; do
    _contract_deployed_networks+=(
      "$(basename \
           "${_network}")"
    )
  done
  _msg=(
    "Found contract '${_target_contract}'"
    "deployments configuration"
    "for networks '${_contract_deployed_networks[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
}

_contract_build() {
  local \
    _contracts_dir="${1}" \
    _target_contract="${2}" \
    _compiler_backend="${3}" \
    _work_dir="${4}" \
    _cache_clean="${5}" \
    _rebuild_skip="${6}" \
    _compiler_opts=() \
    _contract_dirs=() \
    _contract_versions=() \
    _contract_deployed_networks=() \
    _build \
    _build_dir \
    _compiler_work_dir \
    _config_file \
    _deployment \
    _deployment_dir \
    _path_project_json \
    _path_project_sol \
    _network \
    _version \
    _msg=()
  _msg=(
    "Building contract '${_target_contract}'."
  )
  _msg_info \
    "${_msg[*]}"
  _contract_setup \
    "${_contracts_dir}" \
    "${_target_contract}"
  for _network in "${_contract_deployed_networks[@]}"; do
    _deployment_dir="${_contract_deployments_dir}/${_network}"
    if [[ -d "${_deployment_dir}" ]]; then
      _config_file="${_deployment_dir}/config.sh"
      source \
        "${_config_file}"
      for _version in "${!contract_address[@]}"; do
        _deployment="${_network}/${_version}"
        _build_dir="${_work_dir}/${_deployment}"
        _compiler_work_dir="${_build_dir}/build"
        _compiler_opts=()
        if [[ "${quiet}" == "n" ]]; then
          _compiler_opts+=(
            -v
          )
        fi
        if [[ "${_cache_clean}" == "y" ]]; then
          _compiler_opts+=(
            -l
          )
        fi
        _compiler_opts+=(
          -b
            "${_compiler_backend}"
          -C
            "${solc_version["${_version}"]}"
          -e
            "${evm_version["${_version}"]}"
          -w
            "${_compiler_work_dir}"
          -o
            "${_build_dir}"
        )
        mkdir \
          -p \
          "${_compiler_work_dir}"
        _build="true"
        if [[ "${_rebuild_skip}" == "y" ]]; then
          if [[ "${_compiler_backend}" == "solc" ]]; then
            if [[ -e "${_build_dir}/${_abi}" ]] && \
               [[ -e "${_build_dir}/${_bytecode}" ]]; then \
             _build="false"
            fi
          elif [[ "${_compiler_backend}" == "hardhat" ]]; then
            _path_build_json="${_build_dir}/contracts/${_sol}/${_json}"
            _msg=(
              "Looking for '${_path_build_json}'"
            )
            _msg_info \
              "${_msg[*]}"
            if [[ -e "${_path_build_json}" ]]; then
              _build="false"
            fi
          fi
        fi
        if [[ "${_build}" == "true" ]]; then
          _path_project_sol="$(
            realpath \
              "${_contract_dir}/${_version}/${_sol}")"
          _msg=(
            "Building '${_path_project_sol}'."
            "Running 'solidity-compiler' with"
            "options '${_compiler_opts[*]}'."
          )
          _msg_info \
            "${_msg[*]}"
          echo "mammt"
          solidity-compiler \
            "${_compiler_opts[@]}" \
            "${_path_project_sol}"
        elif [[ "${_build}" == "false" ]]; then
          _msg=(
            "Skipping build of '${_path_project_sol}'."
          )
          _msg_info \
            "${_msg[*]}"
        fi
      done
      _contract_built="true"
    else
      _msg=(
        "No deployments for"
        "contract '${_target_contract}'."
      )
      _msg_info \
        "${_msg[*]}"
    fi || \
    true
  done || \
  true
  true
}

_contract_install_common() {
  local \
    _install_opts=()
  if [[ "${quiet}" == "n" ]]; then
    _install_opts+=(
      -v
    )
  fi
  _install_opts+=(
    -dm755
  )
  install \
    "${_install_opts[@]}" \
    "${_lib_dir}"
}

_contract_install_sources() {
  local \
    _contracts_dir="${1}" \
    _target_contract="${2}" \
    _lib_dir="${3}" \
    _contract_dirs=() \
    _contract_versions=() \
    _contract_deployed_networks=() \
    _install_dir \
    _install_opts=() \
    _version
  if [[ "${quiet}" == "n" ]]; then
    _install_opts+=(
      -v
    )
  fi
  _install_opts+=(
    -Dm644
  )
  _contract_install_common
  _contract_setup \
    "${_contracts_dir}" \
    "${_target_contract}"
  _msg_info \
    "Installing sources for '${_target_contract}'"
  for _version in "${_contract_versions[@]}"; do \
    _install_dir="${_lib_dir}/contracts"
    install \
      "${_install_opts[@]}" \
      "${_contract_dir}/${_version}/${_sol}" \
      "${_install_dir}/${_target_contract}/${_version}/${_sol}"
  done
}

_contract_install_deployments_config() {
  local \
    _contracts_dir="${1}" \
    _target_contract="${2}" \
    _lib_dir="${3}" \
    _contract_dirs=() \
    _contract_versions=() \
    _contract_deployed_networks=() \
    _libevm_config_convert_opts=() \
    _msg=() \
    _install_dir \
    _network
  if [[ "${quiet}" == "n" ]]; then
    _libevm_config_convert_opts+=(
      -v
    )
  fi
  _msg=(
    "Installing deployments configurations"
    "for '${_target_contract}'"
  )
  _msg_info \
    "${_msg[*]}"
  _contract_install_common
  _contract_setup \
    "${_contracts_dir}" \
    "${_target_contract}"
  for _network in ${_contract_deployed_networks[@]}; do
    _deployment_dir="${_contract_deployments_dir}/${_network}"
    if [[ -d "${_deployment_dir}" ]]; then
      _config_file="${_deployment_dir}/config.sh"
      _install_dir="${_lib_dir}/deployments/${_target_contract}/${_network}"
      install \
        -Dm644 \
        "${_config_file}" \
        "${_install_dir}/config.sh"
      if [[ " ${target_languages[*]} " == *" javascript "* ]]; then
        libevm-config-convert \
          "${_libevm_config_convert_opts[@]}" \
          "${_config_file}" \
          "${_install_dir}/config.json"
      fi
    fi
  done
}

_contract_install_deployments_solc() {
  local \
    _contracts_dir="${1}" \
    _target_contract="${2}" \
    _lib_dir="${3}" \
    _work_dir="${4}" \
    _contract_dirs=() \
    _contract_versions=() \
    _contract_deployed_networks=() \
    _config_file \
    _build_dir \
    _deployment \
    _install_dir \
    _network \
    _install_opts=()
  if [[ "${quiet}" == "n" ]]; then
    _install_opts+=(
      -v
    )
  _install_opts+=(
    -Dm644
  )
  fi
  _msg=(
    "Installing solc deployments artifacts"
    "for '${_target_contract}'."
  )
  _msg_info \
    "${_msg[*]}"
  _contract_install_common
  _contract_setup \
    "${_contracts_dir}" \
    "${_target_contract}"
  for _network in ${_contract_deployed_networks[@]}; do
    _deployment_dir="${_contract_deployments_dir}/${_network}"
    if [[ -d "${_deployment_dir}" ]]; then
      _config_file="${_deployment_dir}/config.sh"
      source \
        "${_config_file}"
      for _version in "${!contract_address[@]}"; do
        _deployment="${_network}/${_version}"
        _build_dir="${_work_dir}/${_deployment}"
        _install_dir="${_lib_dir}/deployments/${_target_contract}/${_deployment}"
        install \
          "${_install_opts[@]}" \
          "${_build_dir}/${_abi}" \
          "${_install_dir}/${_abi}"
        install \
          "${_install_opts[@]}" \
          "${_build_dir}/${_bytecode}" \
          "${_install_dir}/${_bytecode}"
      done
    else
      _msg=(
        "No deployments for contract"
        "'${_target_contract}'."
      )
      _msg_info \
        "${_msg[*]}"
    fi
  done
}

_contract_install_deployments_hardhat() {
  local \
    _contracts_dir="${1}" \
    _target_contract="${2}" \
    _lib_dir="${3}" \
    _work_dir="${4}" \
    _contract_dirs=() \
    _contract_versions=() \
    _contract_deployed_networks=() \
    _install_opts=() \
    _config_file \
    _build_dir \
    _path_build_json \
    _deployment \
    _install_dir \
    _network
  if [[ "${quiet}" == "n" ]]; then
    _install_opts+=(
      -v
    )
  fi
  install_opts+=(
    -Dm644
  )
  _msg=(
    "Installing hardhat deployments artifacts"
    "for '${_target_contract}'."
  )
  _msg_info \
    "${_msg[*]}"
  _contract_install_common
  _contract_setup \
    "${_contracts_dir}" \
    "${_target_contract}"
  _msg=(
    "Deployments found for networks"
    "'${_contract_deployed_networks[@]}'."
  )
  _msg_info \
    "${_msg[*]}"
  for _network in ${_contract_deployed_networks[@]}; do
    _deployment_dir="${_contract_deployments_dir}/${_network}"
    if [[ -d "${_deployment_dir}" ]]; then
      _config_file="${_deployment_dir}/config.sh";
      source \
        "${_config_file}"
      for _version in "${!contract_address[@]}"; do
        _deployment="${_network}/${_version}"
        _build_dir="${_work_dir}/${_deployment}"
        _install_dir="${_lib_dir}/deployments/${_target_contract}/${_deployment}"
        _path_build_json="${_build_dir}/contracts/${_sol}/${_json}"
        install \
          "${_install_opts[@]}" \
          "${_path_build_json}" \
          "${_install_dir}/${_json}"
      done
    else
      _msg=(
        "No deployments for contract"
        "'${_target_contract}'."
      )
      _msg_info \
        "${_msg[*]}"
    fi
  done
}

_contracts_get() {
  local \
    _contracts_dir="${1}" \
    _contract \
    _contract_name \
    _contracts_dirs=() \
    _msg=()
  _contracts_dirs+=(
    "${_contracts_dir}/"*
  )
  for _contract_dir in "${_contracts_dirs[@]}"; do
    if [[ -d "${_contract_dir}" ]]; then
      _contract_name="$(
        basename \
          "${_contract_dir}")"
      for _path in "${_contract_dir}/"*"/${_contract_name}.sol"; do
        if [[ -e "${_path}" ]]; then
          _contracts+=(
            "${_contract_name}"
          )
          break
        else
          true
          # _msg=(
          #   "Directory '${_contract_dir}'"
          #   "is not a contract directory"
          #   "because '${_path}'"
          #   "does not exist."
          # )
          # _msg_info \
          #   "${_msg[*]}"
        fi
      done
    fi
  done
  _msg=(
    "Found contracts '${_contracts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
}

_evm_make() {
  local \
    _target_command="${1}" \
    _project_dir="${2}" \
    _contracts_dir="${3}" \
    _work_dir="${4}" \
    _compiler_backend="${5}" \
    _lib_dir="${6}" \
    _cache_clean="${7}" \
    _rebuild_skip="${8}" \
    _target_languages_amount="${9}" \
    _target_languages=() \
    _target_actions=() \
    _oldpwd \
    _contract \
    _contract_deployments_dir \
    _contracts=() \
    _contract_built \
    _contracts_dir \
    _sol \
    _abi \
    _bytecode \
    _json \
    _msg=() \
    _command_args=()
  shift \
    9
  for _index \
    in $(seq \
           "$(( "${_target_languages_amount}" -1 ))"); do
    _target_languages+=(
      "${1}"
    )
    shift
  done
  _command_args+=(
    "$@"
  )
  if [[ "${_contracts_dir}" == "" ]]; then
    _contracts_dir="contracts"
  fi
  _oldpwd="${PWD}"
  if [[ "${_target_command}" == "install" ]]; then
    _target_actions+=(
      "install_sources"
      "install_deployments_config"
      "install_deployments"
    )
  elif [[ "${_target_command}" == \
            "build" || \
          "${_target_command}" == \
            "install_sources" || \
          "${_target_command}" == \
            "install_deployments_config" || \
          "${_target_command}" == \
            "install_deployments" ]]; then
    _target_actions+=(
      "${_target_command}"
    )
  fi
  cd \
    "${_project_dir}"
  _contracts_get \
    "${_contracts_dir}"
  for _contract in "${_contracts[@]}"; do
    if [[ " ${_target_actions[*]} " == \
            *" build "* ]]; then
      _contract_build \
        "${_contracts_dir}" \
        "${_contract}" \
        "${_compiler_backend}" \
        "${_work_dir}" \
        "${_cache_clean}" \
        "${_rebuild_skip}" || \
      true
    fi
    if [[ " ${_target_actions[*]} " == \
            *" install_sources "* ]]; then
      _contract_install_sources \
        "${_contracts_dir}" \
        "${_contract}" \
        "${_lib_dir}"
    fi
    if [[ " ${_target_actions[*]} " == \
            *" install_deployments_config "* ]]; then
      _contract_install_deployments_config \
        "${_contracts_dir}" \
        "${_contract}" \
        "${_lib_dir}"
    fi
    if [[ " ${_target_actions[*]} " == \
            *" install_deployments "* ]]; then
      "_contract_install_deployments_${_compiler_backend}" \
        "${_contracts_dir}" \
        "${_contract}" \
        "${_lib_dir}" \
        "${_work_dir}" || \
      true
    fi
  done
  cd \
    "${_oldpwd}"
}

_cache_clean_auto_detect() {
  local \
    _clean \
    _backend
  _backend="${compiler_backend}"
  if [[ "${_backend}" == "hardhat" ]]; then
    _clean="y"
  elif [[ "${_backend}" == "solc" ]]; then
    _clean="n"
  fi
  _set_override \
    "cache" \
    "clean" \
    "${_clean}"
}

_project_dir_check() {
  local \
    _msg=() \
    _realpath
  if [[ ! -e "${project_dir}" ]]; then
    _msg+=(
      "Project directory"
      "'${project_dir}'"
      "does not exist."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  _realpath="$(
    realpath \
      "${project_dir}")"
  if [[ -e "${_realpath}" ]]; then
    project_dir="${_realpath}"
  fi
}

_contracts_dir_auto_detect() {
  local \
    _contracts_dir
  _contracts_dir="contracts"
  if [[ ! -d "${project_dir}/${_contracts_dir}" ]]; then
    _contracts_dir="${project_dir}"
  fi
  _set_override \
    "contracts" \
    "dir" \
    "${_contracts_dir}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ "${target_languages[*]}" == "" ]]; then
    target_languages=(
      "bash"
      "javascript"
    )
  fi
  target_languages_amount="${#target_languages[@]}"
  _set_override \
    "make" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "project" \
    "dir" \
    "$(realpath \
         "${PWD}")"
  _project_dir_check
  _set_override \
    "work" \
    "dir" \
    "$(_work_dir_auto_detect)"
  _set_override \
    "lib" \
    "dir" \
    "${PWD}/build"
  _set_override \
    "rebuild" \
    "skip" \
    "n"
  _set_override \
    "compiler" \
    "backend" \
    "solc"
  _cache_clean_auto_detect
  _contracts_dir_auto_detect
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit="${1}"
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

EVM toolchain build and install tool.

Usage:

  ${app_name}
    [options]
    <command>

  commands:

    build
    install
    install_sources
    install_deployments_config
    install_deployments
    Default: ${target_command}

  options:

     -C <project-dir>       Project directory.
                            Default: ${project_dir}

     -p <contracts-dir>     Contracts directory inside
                            the project.
                            Default: ${contracts_dir}

     -b <compiler-backend>  Backend for solidity-compiler;
                            can be 'solc' or 'hardhat'.
                            Default: ${compiler_backend}

     -w <work-dir>          Work directory.
                            Default: ${work_dir}

     -o <lib-dir>           Install directory.
                            Default: ${lib_dir}

     -l <y/n>               Whether to pass the clean cache
                            option to solidity-compiler.
                            When the backend is 'hardhat'
                            defaults to 'y', while for 'solc' is 'n'.
                            Default: ${cache_clean}

     -L <language>          Target languages for the configuration file.
                            It can be 'bash' or 'javascript'.
                            Default: ${target_languages[@]}

     -f <y/n>               If 'y', skip rebuilding the contracts
                            if artifacts are found already in the
                            directory.

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Make date:   ${make_date}"
  _msg_info "           Target command:   ${target_command}"
  _msg_info "        Project directory:   ${project_dir}"
  _msg_info "      Contracts directory:   ${contracts_dir}"
  _msg_info "           Work directory:   ${work_dir}"
  _msg_info "        Install directory:   ${lib_dir}"
  _msg_info "         Compiler backend:   ${compiler_backend}"
  _msg_info "              Cache clean:   ${cache_clean}"
  _msg_info "             Skip rebuild:   ${rebuild_skip}"
  _msg_info "         Target languages:   ${rebuild_skip}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    'C:p:w:o:b:l:L:f:cvh?' \
    arg; do
  case \
    "${arg}" in
    C)
      override_project_dir="${OPTARG}" ;;
    p)
      override_contracts_dir="${OPTARG}" ;;
    w)
      override_work_dir="$(
        realpath \
          "${OPTARG}")" ;;
    o)
      override_lib_dir="${OPTARG}" ;;
    b)
      override_compiler_backend="${OPTARG}" ;;
    l)
      override_cache_clean="${OPTARG}" ;;
    L)
      target_languages+=(
        "${OPTARG}"
      ) ;;
    f)
      override_rebuild_skip="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  target_command="build"
fi
if (( 0 < $# )); then
  target_command="${1}"
fi
shift \
  1 || \
  true
command_args+=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${target_command}"
  "${project_dir}"
  "${contracts_dir}"
  "${work_dir}"
  "${compiler_backend}"
  "${lib_dir}"
  "${cache_clean}"
  "${rebuild_skip}"
  "${target_languages_amount}"
  "${target_languages[@]}"
)
_evm_make \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
